// MenOnDemand-v2/src/main/webapp/app/entities/payment-record/payment-record.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { filter, map } from 'rxjs/operators';
import { JhiEventManager } from 'ng-jhipster';

import { IPaymentRecord } from 'app/shared/model/payment-record.model';
import { AccountService } from 'app/core/auth/account.service';
import { PaymentRecordService } from './payment-record.service';

@Component({
  selector: 'jhi-payment-record',
  templateUrl: './payment-record.component.html'
})
export class PaymentRecordComponent implements OnInit, OnDestroy {
  paymentRecords: IPaymentRecord[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected paymentRecordService: PaymentRecordService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.paymentRecordService
      .query()
      .pipe(
        filter((res: HttpResponse<IPaymentRecord[]>) => res.ok),
        map((res: HttpResponse<IPaymentRecord[]>) => res.body)
      )
      .subscribe((res: IPaymentRecord[]) => {
        this.paymentRecords = res;
      });
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().subscribe(account => {
      this.currentAccount = account;
    });
    this.registerChangeInPaymentRecords();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IPaymentRecord) {
    return item.id;
  }

  registerChangeInPaymentRecords() {
    this.eventSubscriber = this.eventManager.subscribe('paymentRecordListModification', response => this.loadAll());
  }
}

<div>
    <h2 id="page-heading">
        <span>Payment Records</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-payment-record" [routerLink]="['/payment-record/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span >
            Create a new Payment Record
            </span>
        </button>
    </h2>
    <jhi-alert-error></jhi-alert-error>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="paymentRecords?.length === 0">
        <span>No paymentRecords found</span>
    </div>
    <div class="table-responsive" *ngIf="paymentRecords?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
            <tr>
            <th scope="col" ><span>ID</span></th>
            <th scope="col" ><span>Txn Type</span></th>
            <th scope="col" ><span>Amount</span></th>
            <th scope="col" ><span>Total Amount To Mentor</span></th>
            <th scope="col" ><span>Issued Time</span></th>
            <th scope="col" ><span>Remarks</span></th>
            <th scope="col" ><span>User</span></th>
            <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let paymentRecord of paymentRecords ;trackBy: trackId">
                <td><a [routerLink]="['/payment-record', paymentRecord.id, 'view' ]">{{paymentRecord.id}}</a></td>
                <td>{{paymentRecord.txnType}}</td>
                <td>{{paymentRecord.amount}}</td>
                <td>{{paymentRecord.totalAmountToMentor}}</td>
                <td>{{paymentRecord.issuedTime | date:'medium'}}</td>
                <td>{{paymentRecord.remarks}}</td>
                <td>
                    {{paymentRecord.user?.userName}}
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/payment-record', paymentRecord.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/payment-record', paymentRecord.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/payment-record', { outlets: { popup: paymentRecord.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// gateway-jwt/src/main/webapp/app/entities/payment-record/payment-record.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { ICrudGetAllAction, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './payment-record.reducer';
import { IPaymentRecord } from 'app/shared/model/payment-record.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';

export interface IPaymentRecordProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export type IPaymentRecordState = IPaginationBaseState;

export class PaymentRecord extends React.Component<IPaymentRecordProps, IPaymentRecordState> {
  state: IPaymentRecordState = {
    ...getSortState(this.props.location, ITEMS_PER_PAGE)
  };

  componentDidMount() {
    this.getEntities();
  }

  sort = prop => () => {
    this.setState(
      {
        order: this.state.order === 'asc' ? 'desc' : 'asc',
        sort: prop
      },
      () => this.sortEntities()
    );
  };

  sortEntities() {
    this.getEntities();
    this.props.history.push(`${this.props.location.pathname}?page=${this.state.activePage}&sort=${this.state.sort},${this.state.order}`);
  }

  handlePagination = activePage => this.setState({ activePage }, () => this.sortEntities());

  getEntities = () => {
    const { activePage, itemsPerPage, sort, order } = this.state;
    this.props.getEntities(activePage - 1, itemsPerPage, `${sort},${order}`);
  };

  render() {
    const { paymentRecordList, match, totalItems } = this.props;
    return (
      <div>
        <h2 id="payment-record-heading">
          Payment Records
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp; Create a new Payment Record
          </Link>
        </h2>
        <div className="table-responsive">
          {paymentRecordList && paymentRecordList.length > 0 ? (
            <Table responsive aria-describedby="payment-record-heading">
              <thead>
                <tr>
                  <th className="hand" onClick={this.sort('id')}>
                    ID <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('txnType')}>
                    Txn Type <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('amount')}>
                    Amount <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('mentorId')}>
                    Mentor Id <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('mentorName')}>
                    Mentor Name <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('trainingId')}>
                    Training Id <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('skillName')}>
                    Skill Name <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('totalAmountToMentor')}>
                    Total Amount To Mentor <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('remarks')}>
                    Remarks <FontAwesomeIcon icon="sort" />
                  </th>
                  <th>
                    User <FontAwesomeIcon icon="sort" />
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {paymentRecordList.map((paymentRecord, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${paymentRecord.id}`} color="link" size="sm">
                        {paymentRecord.id}
                      </Button>
                    </td>
                    <td>{paymentRecord.txnType}</td>
                    <td>{paymentRecord.amount}</td>
                    <td>{paymentRecord.mentorId}</td>
                    <td>{paymentRecord.mentorName}</td>
                    <td>{paymentRecord.trainingId}</td>
                    <td>{paymentRecord.skillName}</td>
                    <td>{paymentRecord.totalAmountToMentor}</td>
                    <td>{paymentRecord.remarks}</td>
                    <td>{paymentRecord.user ? <Link to={`member/${paymentRecord.user.id}`}>{paymentRecord.user.id}</Link> : ''}</td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${paymentRecord.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${paymentRecord.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${paymentRecord.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">No Payment Records found</div>
          )}
        </div>
        <div className={paymentRecordList && paymentRecordList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={this.state.activePage} total={totalItems} itemsPerPage={this.state.itemsPerPage} />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={this.state.activePage}
              onSelect={this.handlePagination}
              maxButtons={5}
              itemsPerPage={this.state.itemsPerPage}
              totalItems={this.props.totalItems}
            />
          </Row>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ paymentRecord }: IRootState) => ({
  paymentRecordList: paymentRecord.entities,
  totalItems: paymentRecord.totalItems
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(PaymentRecord);
