// gateway-jwt-ng/src/main/webapp/app/entities/training/training-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import * as moment from 'moment';
import { DATE_TIME_FORMAT } from 'app/shared/constants/input.constants';
import { ITraining, Training } from 'app/shared/model/training.model';
import { TrainingService } from './training.service';

@Component({
  selector: 'jhi-training-update',
  templateUrl: './training-update.component.html'
})
export class TrainingUpdateComponent implements OnInit {
  isSaving: boolean;

  editForm = this.fb.group({
    id: [],
    status: [null, [Validators.required]],
    name: [null, [Validators.required]],
    commissionAmount: [null, [Validators.required]],
    avgRating: [],
    startDate: [],
    endDate: [],
    mentorId: [],
    mentorName: [],
    skillName: [null, [Validators.required]],
    remarks: []
  });

  constructor(protected trainingService: TrainingService, protected activatedRoute: ActivatedRoute, private fb: FormBuilder) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ training }) => {
      this.updateForm(training);
    });
  }

  updateForm(training: ITraining) {
    this.editForm.patchValue({
      id: training.id,
      status: training.status,
      name: training.name,
      commissionAmount: training.commissionAmount,
      avgRating: training.avgRating,
      startDate: training.startDate != null ? training.startDate.format(DATE_TIME_FORMAT) : null,
      endDate: training.endDate != null ? training.endDate.format(DATE_TIME_FORMAT) : null,
      mentorId: training.mentorId,
      mentorName: training.mentorName,
      skillName: training.skillName,
      remarks: training.remarks
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const training = this.createFromForm();
    if (training.id !== undefined) {
      this.subscribeToSaveResponse(this.trainingService.update(training));
    } else {
      this.subscribeToSaveResponse(this.trainingService.create(training));
    }
  }

  private createFromForm(): ITraining {
    return {
      ...new Training(),
      id: this.editForm.get(['id']).value,
      status: this.editForm.get(['status']).value,
      name: this.editForm.get(['name']).value,
      commissionAmount: this.editForm.get(['commissionAmount']).value,
      avgRating: this.editForm.get(['avgRating']).value,
      startDate:
        this.editForm.get(['startDate']).value != null ? moment(this.editForm.get(['startDate']).value, DATE_TIME_FORMAT) : undefined,
      endDate: this.editForm.get(['endDate']).value != null ? moment(this.editForm.get(['endDate']).value, DATE_TIME_FORMAT) : undefined,
      mentorId: this.editForm.get(['mentorId']).value,
      mentorName: this.editForm.get(['mentorName']).value,
      skillName: this.editForm.get(['skillName']).value,
      remarks: this.editForm.get(['remarks']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ITraining>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-training-heading">Create or edit a Training</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_status">Status</label>
                    <select class="form-control" name="status" formControlName="status" id="field_status">
                        <option value="Active">Active</option>
                        <option value="Inactive">Inactive</option>
                    </select>
                    <div *ngIf="editForm.get('status').invalid && (editForm.get('status').dirty || editForm.get('status').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('status').errors.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_name">Name</label>
                    <input type="text" class="form-control" name="name" id="field_name"
                           formControlName="name"/>
                    <div *ngIf="editForm.get('name').invalid && (editForm.get('name').dirty || editForm.get('name').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('name').errors.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_commissionAmount">Commission Amount</label>
                    <input type="number" class="form-control" name="commissionAmount" id="field_commissionAmount"
                           formControlName="commissionAmount"/>
                    <div *ngIf="editForm.get('commissionAmount').invalid && (editForm.get('commissionAmount').dirty || editForm.get('commissionAmount').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('commissionAmount').errors.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('commissionAmount')?.errors?.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_avgRating">Avg Rating</label>
                    <input type="number" class="form-control" name="avgRating" id="field_avgRating"
                           formControlName="avgRating"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_startDate">Start Date</label>
                    <div class="d-flex">
                        <input id="field_startDate" type="datetime-local" class="form-control" name="startDate" formControlName="startDate" placeholder="YYYY-MM-DD HH:mm"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_endDate">End Date</label>
                    <div class="d-flex">
                        <input id="field_endDate" type="datetime-local" class="form-control" name="endDate" formControlName="endDate" placeholder="YYYY-MM-DD HH:mm"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_mentorId">Mentor Id</label>
                    <input type="number" class="form-control" name="mentorId" id="field_mentorId"
                           formControlName="mentorId"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_mentorName">Mentor Name</label>
                    <input type="text" class="form-control" name="mentorName" id="field_mentorName"
                           formControlName="mentorName"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_skillName">Skill Name</label>
                    <input type="text" class="form-control" name="skillName" id="field_skillName"
                           formControlName="skillName"/>
                    <div *ngIf="editForm.get('skillName').invalid && (editForm.get('skillName').dirty || editForm.get('skillName').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('skillName').errors.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="field_remarks">Remarks</label>
                    <input type="text" class="form-control" name="remarks" id="field_remarks"
                           formControlName="remarks"/>
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span>Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span>Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// gateway-jwt/src/main/webapp/app/entities/training/training-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './training.reducer';
import { ITraining } from 'app/shared/model/training.model';
import { convertDateTimeFromServer, convertDateTimeToServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface ITrainingUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface ITrainingUpdateState {
  isNew: boolean;
}

export class TrainingUpdate extends React.Component<ITrainingUpdateProps, ITrainingUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentWillUpdate(nextProps, nextState) {
    if (nextProps.updateSuccess !== this.props.updateSuccess && nextProps.updateSuccess) {
      this.handleClose();
    }
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }
  }

  saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const { trainingEntity } = this.props;
      const entity = {
        ...trainingEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/training');
  };

  render() {
    const { trainingEntity, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="gatewayApp.training.home.createOrEditLabel">Create or edit a Training</h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : trainingEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="training-id">ID</Label>
                    <AvInput id="training-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="statusLabel" for="training-status">
                    Status
                  </Label>
                  <AvInput
                    id="training-status"
                    type="select"
                    className="form-control"
                    name="status"
                    value={(!isNew && trainingEntity.status) || 'Active'}
                  >
                    <option value="Active">Active</option>
                    <option value="Inactive">Inactive</option>
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label id="commissionAmountLabel" for="training-commissionAmount">
                    Commission Amount
                  </Label>
                  <AvField
                    id="training-commissionAmount"
                    type="string"
                    className="form-control"
                    name="commissionAmount"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' },
                      number: { value: true, errorMessage: 'This field should be a number.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="avgRatingLabel" for="training-avgRating">
                    Avg Rating
                  </Label>
                  <AvField id="training-avgRating" type="string" className="form-control" name="avgRating" />
                </AvGroup>
                <AvGroup>
                  <Label id="startDateLabel" for="training-startDate">
                    Start Date
                  </Label>
                  <AvField
                    id="training-startDate"
                    type="text"
                    name="startDate"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="endDateLabel" for="training-endDate">
                    End Date
                  </Label>
                  <AvField
                    id="training-endDate"
                    type="text"
                    name="endDate"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="startTimeLabel" for="training-startTime">
                    Start Time
                  </Label>
                  <AvField
                    id="training-startTime"
                    type="text"
                    name="startTime"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="endTimeLabel" for="training-endTime">
                    End Time
                  </Label>
                  <AvField
                    id="training-endTime"
                    type="text"
                    name="endTime"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="mentorIdLabel" for="training-mentorId">
                    Mentor Id
                  </Label>
                  <AvField
                    id="training-mentorId"
                    type="string"
                    className="form-control"
                    name="mentorId"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' },
                      number: { value: true, errorMessage: 'This field should be a number.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="mentorNameLabel" for="training-mentorName">
                    Mentor Name
                  </Label>
                  <AvField
                    id="training-mentorName"
                    type="text"
                    name="mentorName"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="skillNameLabel" for="training-skillName">
                    Skill Name
                  </Label>
                  <AvField
                    id="training-skillName"
                    type="text"
                    name="skillName"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="feesLabel" for="training-fees">
                    Fees
                  </Label>
                  <AvField
                    id="training-fees"
                    type="string"
                    className="form-control"
                    name="fees"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' },
                      number: { value: true, errorMessage: 'This field should be a number.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="remarksLabel" for="training-remarks">
                    Remarks
                  </Label>
                  <AvField id="training-remarks" type="text" name="remarks" />
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/training" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">Back</span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp; Save
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  trainingEntity: storeState.training.entity,
  loading: storeState.training.loading,
  updating: storeState.training.updating,
  updateSuccess: storeState.training.updateSuccess
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(TrainingUpdate);
