// MentorOnDemand/src/main/webapp/app/entities/member/member.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { filter, map } from 'rxjs/operators';
import { JhiEventManager } from 'ng-jhipster';

import { IMember } from 'app/shared/model/member.model';
import { AccountService } from 'app/core/auth/account.service';
import { MemberService } from './member.service';

@Component({
  selector: 'jhi-member',
  templateUrl: './member.component.html'
})
export class MemberComponent implements OnInit, OnDestroy {
  members: IMember[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(protected memberService: MemberService, protected eventManager: JhiEventManager, protected accountService: AccountService) {}

  loadAll() {
    this.memberService
      .query()
      .pipe(
        filter((res: HttpResponse<IMember[]>) => res.ok),
        map((res: HttpResponse<IMember[]>) => res.body)
      )
      .subscribe((res: IMember[]) => {
        this.members = res;
      });
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().subscribe(account => {
      this.currentAccount = account;
    });
    this.registerChangeInMembers();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IMember) {
    return item.id;
  }

  registerChangeInMembers() {
    this.eventSubscriber = this.eventManager.subscribe('memberListModification', response => this.loadAll());
  }
}

<div>
    <h2 id="page-heading">
        <span>Members</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-member" [routerLink]="['/member/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span >
            Create a new Member
            </span>
        </button>
    </h2>
    <jhi-alert-error></jhi-alert-error>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="members?.length === 0">
        <span>No members found</span>
    </div>
    <div class="table-responsive" *ngIf="members?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
            <tr>
            <th scope="col" ><span>ID</span></th>
            <th scope="col" ><span>Type</span></th>
            <th scope="col" ><span>User Name</span></th>
            <th scope="col" ><span>Name</span></th>
            <th scope="col" ><span>User</span></th>
            <th scope="col" ><span>Mentor</span></th>
            <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let member of members ;trackBy: trackId">
                <td><a [routerLink]="['/member', member.id, 'view' ]">{{member.id}}</a></td>
                <td>{{member.type}}</td>
                <td>{{member.userName}}</td>
                <td>{{member.name}}</td>
                <td>
                    <div *ngIf="member.user">
                        <a [routerLink]="['/member', member.user?.id, 'view' ]" >{{member.user?.id}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="member.mentor">
                        <a [routerLink]="['/mentor', member.mentor?.id, 'view' ]" >{{member.mentor?.id}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/member', member.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/member', member.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/member', { outlets: { popup: member.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// gateway-jwt/src/main/webapp/app/entities/member/member.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './member.reducer';
import { IMember } from 'app/shared/model/member.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IMemberProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class Member extends React.Component<IMemberProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { memberList, match } = this.props;
    return (
      <div>
        <h2 id="member-heading">
          Members
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp; Create a new Member
          </Link>
        </h2>
        <div className="table-responsive">
          {memberList && memberList.length > 0 ? (
            <Table responsive aria-describedby="member-heading">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {memberList.map((member, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${member.id}`} color="link" size="sm">
                        {member.id}
                      </Button>
                    </td>
                    <td>{member.name}</td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${member.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${member.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${member.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">No Members found</div>
          )}
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ member }: IRootState) => ({
  memberList: member.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Member);
