// gateway-jwt2/src/main/webapp/app/entities/training/training.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './training.reducer';
import { ITraining } from 'app/shared/model/training.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ITrainingProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class Training extends React.Component<ITrainingProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { trainingList, match } = this.props;
    return (
      <div>
        <h2 id="training-heading">
          Trainings
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp; Create a new Training
          </Link>
        </h2>
        <div className="table-responsive">
          {trainingList && trainingList.length > 0 ? (
            <Table responsive aria-describedby="training-heading">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Status</th>
                  <th>Commission Amount</th>
                  <th>Avg Rating</th>
                  <th>Start Date</th>
                  <th>End Date</th>
                  <th>Start Time</th>
                  <th>End Time</th>
                  <th>Mentor Id</th>
                  <th>Mentor Name</th>
                  <th>Skill Name</th>
                  <th>Fees</th>
                  <th>Remarks</th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {trainingList.map((training, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${training.id}`} color="link" size="sm">
                        {training.id}
                      </Button>
                    </td>
                    <td>{training.status}</td>
                    <td>{training.commissionAmount}</td>
                    <td>{training.avgRating}</td>
                    <td>{training.startDate}</td>
                    <td>{training.endDate}</td>
                    <td>{training.startTime}</td>
                    <td>{training.endTime}</td>
                    <td>{training.mentorId}</td>
                    <td>{training.mentorName}</td>
                    <td>{training.skillName}</td>
                    <td>{training.fees}</td>
                    <td>{training.remarks}</td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${training.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${training.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${training.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">No Trainings found</div>
          )}
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ training }: IRootState) => ({
  trainingList: training.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Training);

// gateway-jwt-ng/src/main/webapp/app/entities/training/training.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { filter, map } from 'rxjs/operators';
import { JhiEventManager } from 'ng-jhipster';

import { ITraining } from 'app/shared/model/training.model';
import { AccountService } from 'app/core/auth/account.service';
import { TrainingService } from './training.service';

@Component({
  selector: 'jhi-training',
  templateUrl: './training.component.html'
})
export class TrainingComponent implements OnInit, OnDestroy {
  trainings: ITraining[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected trainingService: TrainingService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.trainingService
      .query()
      .pipe(
        filter((res: HttpResponse<ITraining[]>) => res.ok),
        map((res: HttpResponse<ITraining[]>) => res.body)
      )
      .subscribe((res: ITraining[]) => {
        this.trainings = res;
      });
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().subscribe(account => {
      this.currentAccount = account;
    });
    this.registerChangeInTrainings();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: ITraining) {
    return item.id;
  }

  registerChangeInTrainings() {
    this.eventSubscriber = this.eventManager.subscribe('trainingListModification', response => this.loadAll());
  }
}

<div>
    <h2 id="page-heading">
        <span>Trainings</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-training" [routerLink]="['/training/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span >
            Create a new Training
            </span>
        </button>
    </h2>
    <jhi-alert-error></jhi-alert-error>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="trainings?.length === 0">
        <span>No trainings found</span>
    </div>
    <div class="table-responsive" *ngIf="trainings?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
            <tr>
            <th scope="col" ><span>ID</span></th>
            <th scope="col" ><span>Status</span></th>
            <th scope="col" ><span>Name</span></th>
            <th scope="col" ><span>Commission Amount</span></th>
            <th scope="col" ><span>Avg Rating</span></th>
            <th scope="col" ><span>Start Date</span></th>
            <th scope="col" ><span>End Date</span></th>
            <th scope="col" ><span>Mentor Id</span></th>
            <th scope="col" ><span>Mentor Name</span></th>
            <th scope="col" ><span>Skill Name</span></th>
            <th scope="col" ><span>Remarks</span></th>
            <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let training of trainings ;trackBy: trackId">
                <td><a [routerLink]="['/training', training.id, 'view' ]">{{training.id}}</a></td>
                <td>{{training.status}}</td>
                <td>{{training.name}}</td>
                <td>{{training.commissionAmount}}</td>
                <td>{{training.avgRating}}</td>
                <td>{{training.startDate | date:'medium'}}</td>
                <td>{{training.endDate | date:'medium'}}</td>
                <td>{{training.mentorId}}</td>
                <td>{{training.mentorName}}</td>
                <td>{{training.skillName}}</td>
                <td>{{training.remarks}}</td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/training', training.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/training', training.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/training', { outlets: { popup: training.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
