// gateway-jwt2/src/main/webapp/app/entities/training-record/training-record.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { ICrudGetAllAction, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './training-record.reducer';
import { ITrainingRecord } from 'app/shared/model/training-record.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';

export interface ITrainingRecordProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export type ITrainingRecordState = IPaginationBaseState;

export class TrainingRecord extends React.Component<ITrainingRecordProps, ITrainingRecordState> {
  state: ITrainingRecordState = {
    ...getSortState(this.props.location, ITEMS_PER_PAGE)
  };

  componentDidMount() {
    this.getEntities();
  }

  sort = prop => () => {
    this.setState(
      {
        order: this.state.order === 'asc' ? 'desc' : 'asc',
        sort: prop
      },
      () => this.sortEntities()
    );
  };

  sortEntities() {
    this.getEntities();
    this.props.history.push(`${this.props.location.pathname}?page=${this.state.activePage}&sort=${this.state.sort},${this.state.order}`);
  }

  handlePagination = activePage => this.setState({ activePage }, () => this.sortEntities());

  getEntities = () => {
    const { activePage, itemsPerPage, sort, order } = this.state;
    this.props.getEntities(activePage - 1, itemsPerPage, `${sort},${order}`);
  };

  render() {
    const { trainingRecordList, match, totalItems } = this.props;
    return (
      <div>
        <h2 id="training-record-heading">
          Training Records
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp; Create a new Training Record
          </Link>
        </h2>
        <div className="table-responsive">
          {trainingRecordList && trainingRecordList.length > 0 ? (
            <Table responsive aria-describedby="training-record-heading">
              <thead>
                <tr>
                  <th className="hand" onClick={this.sort('id')}>
                    ID <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('status')}>
                    Status <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('progress')}>
                    Progress <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('commissionAmount')}>
                    Commission Amount <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('avgRating')}>
                    Avg Rating <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('startDate')}>
                    Start Date <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('endDate')}>
                    End Date <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('startTime')}>
                    Start Time <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('endTime')}>
                    End Time <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('amountReceived')}>
                    Amount Received <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('userName')}>
                    User Name <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('skillName')}>
                    Skill Name <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('fees')}>
                    Fees <FontAwesomeIcon icon="sort" />
                  </th>
                  <th className="hand" onClick={this.sort('remarks')}>
                    Remarks <FontAwesomeIcon icon="sort" />
                  </th>
                  <th>
                    User <FontAwesomeIcon icon="sort" />
                  </th>
                  <th>
                    Training <FontAwesomeIcon icon="sort" />
                  </th>
                  <th>
                    Skill <FontAwesomeIcon icon="sort" />
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {trainingRecordList.map((trainingRecord, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${trainingRecord.id}`} color="link" size="sm">
                        {trainingRecord.id}
                      </Button>
                    </td>
                    <td>{trainingRecord.status}</td>
                    <td>{trainingRecord.progress}</td>
                    <td>{trainingRecord.commissionAmount}</td>
                    <td>{trainingRecord.avgRating}</td>
                    <td>{trainingRecord.startDate}</td>
                    <td>{trainingRecord.endDate}</td>
                    <td>{trainingRecord.startTime}</td>
                    <td>{trainingRecord.endTime}</td>
                    <td>{trainingRecord.amountReceived}</td>
                    <td>{trainingRecord.userName}</td>
                    <td>{trainingRecord.skillName}</td>
                    <td>{trainingRecord.fees}</td>
                    <td>{trainingRecord.remarks}</td>
                    <td>{trainingRecord.user ? <Link to={`member/${trainingRecord.user.id}`}>{trainingRecord.user.id}</Link> : ''}</td>
                    <td>
                      {trainingRecord.training ? (
                        <Link to={`training/${trainingRecord.training.id}`}>{trainingRecord.training.id}</Link>
                      ) : (
                        ''
                      )}
                    </td>
                    <td>{trainingRecord.skill ? <Link to={`skill/${trainingRecord.skill.id}`}>{trainingRecord.skill.id}</Link> : ''}</td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${trainingRecord.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${trainingRecord.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${trainingRecord.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">No Training Records found</div>
          )}
        </div>
        <div className={trainingRecordList && trainingRecordList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={this.state.activePage} total={totalItems} itemsPerPage={this.state.itemsPerPage} />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={this.state.activePage}
              onSelect={this.handlePagination}
              maxButtons={5}
              itemsPerPage={this.state.itemsPerPage}
              totalItems={this.props.totalItems}
            />
          </Row>
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ trainingRecord }: IRootState) => ({
  trainingRecordList: trainingRecord.entities,
  totalItems: trainingRecord.totalItems
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(TrainingRecord);

// zuul-gateway/src/main/webapp/app/entities/trainings/training-record/training-record.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiParseLinks } from 'ng-jhipster';

import { ITrainingRecord } from 'app/shared/model/trainings/training-record.model';
import { AccountService } from 'app/core/auth/account.service';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { TrainingRecordService } from './training-record.service';

@Component({
  selector: 'jhi-training-record',
  templateUrl: './training-record.component.html'
})
export class TrainingRecordComponent implements OnInit, OnDestroy {
  currentAccount: any;
  trainingRecords: ITrainingRecord[];
  error: any;
  success: any;
  eventSubscriber: Subscription;
  routeData: any;
  links: any;
  totalItems: any;
  itemsPerPage: any;
  page: any;
  predicate: any;
  previousPage: any;
  reverse: any;

  constructor(
    protected trainingRecordService: TrainingRecordService,
    protected parseLinks: JhiParseLinks,
    protected accountService: AccountService,
    protected activatedRoute: ActivatedRoute,
    protected router: Router,
    protected eventManager: JhiEventManager
  ) {
    this.itemsPerPage = ITEMS_PER_PAGE;
    this.routeData = this.activatedRoute.data.subscribe(data => {
      this.page = data.pagingParams.page;
      this.previousPage = data.pagingParams.page;
      this.reverse = data.pagingParams.ascending;
      this.predicate = data.pagingParams.predicate;
    });
  }

  loadAll() {
    this.trainingRecordService
      .query({
        page: this.page - 1,
        size: this.itemsPerPage,
        sort: this.sort()
      })
      .subscribe((res: HttpResponse<ITrainingRecord[]>) => this.paginateTrainingRecords(res.body, res.headers));
  }

  loadPage(page: number) {
    if (page !== this.previousPage) {
      this.previousPage = page;
      this.transition();
    }
  }

  transition() {
    this.router.navigate(['/training-record'], {
      queryParams: {
        page: this.page,
        size: this.itemsPerPage,
        sort: this.predicate + ',' + (this.reverse ? 'asc' : 'desc')
      }
    });
    this.loadAll();
  }

  clear() {
    this.page = 0;
    this.router.navigate([
      '/training-record',
      {
        page: this.page,
        sort: this.predicate + ',' + (this.reverse ? 'asc' : 'desc')
      }
    ]);
    this.loadAll();
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().subscribe(account => {
      this.currentAccount = account;
    });
    this.registerChangeInTrainingRecords();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: ITrainingRecord) {
    return item.id;
  }

  registerChangeInTrainingRecords() {
    this.eventSubscriber = this.eventManager.subscribe('trainingRecordListModification', response => this.loadAll());
  }

  sort() {
    const result = [this.predicate + ',' + (this.reverse ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected paginateTrainingRecords(data: ITrainingRecord[], headers: HttpHeaders) {
    this.links = this.parseLinks.parse(headers.get('link'));
    this.totalItems = parseInt(headers.get('X-Total-Count'), 10);
    this.trainingRecords = data;
  }
}

<div>
    <h2 id="page-heading">
        <span>Training Records</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-training-record" [routerLink]="['/training-record/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span >
            Create a new Training Record
            </span>
        </button>
    </h2>
    <jhi-alert-error></jhi-alert-error>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="trainingRecords?.length === 0">
        <span>No trainingRecords found</span>
    </div>
    <div class="table-responsive" *ngIf="trainingRecords?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
            <tr jhiSort [(predicate)]="predicate" [(ascending)]="reverse" [callback]="transition.bind(this)">
            <th scope="col"  jhiSortBy="id"><span>ID</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th scope="col"  jhiSortBy="status"><span>Status</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th scope="col"  jhiSortBy="progress"><span>Progress</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th scope="col"  jhiSortBy="commissionAmount"><span>Commission Amount</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th scope="col"  jhiSortBy="avgRating"><span>Avg Rating</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th scope="col"  jhiSortBy="amountReceived"><span>Amount Received</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th scope="col"  jhiSortBy="userName"><span>User Name</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th scope="col"  jhiSortBy="fees"><span>Fees</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th scope="col"  jhiSortBy="remarks"><span>Remarks</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th scope="col"  jhiSortBy="training.name"><span>Training</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let trainingRecord of trainingRecords ;trackBy: trackId">
                <td><a [routerLink]="['/training-record', trainingRecord.id, 'view' ]">{{trainingRecord.id}}</a></td>
                <td>{{trainingRecord.status}}</td>
                <td>{{trainingRecord.progress}}</td>
                <td>{{trainingRecord.commissionAmount}}</td>
                <td>{{trainingRecord.avgRating}}</td>
                <td>{{trainingRecord.amountReceived}}</td>
                <td>{{trainingRecord.userName}}</td>
                <td>{{trainingRecord.fees}}</td>
                <td>{{trainingRecord.remarks}}</td>
                <td>
                    <div *ngIf="trainingRecord.training">
                        <a [routerLink]="['/training', trainingRecord.training?.id, 'view' ]" >{{trainingRecord.training?.name}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/training-record', trainingRecord.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/training-record', trainingRecord.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/training-record', { outlets: { popup: trainingRecord.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <div [hidden]="trainingRecords?.length === 0">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>
        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="page" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage(page)"></ngb-pagination>
        </div>
    </div>
</div>
